name: greencare
description: "A Farmer Advisory System"
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  weather: ^3.1.1
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.0.0 # Ensure the version is compatible with other packages
  firebase_core: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/login.jpg
    - assets/images/sunny.jpg
    - assets/icons/camera.png
    - assets/icons/help.png
    - assets/icons/history.png
    - assets/icons/home.png
    - assets/icons/weather_module.png
    - assets/icons/avatar.png
    - assets/images/image.png
    - assets/images/camera.png
    - assets/images/wheather_check.jpeg


  uses-material-design: true
