// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZWpi8JHWtIGZ1KAXCBKEGogTjDrbuIU',
    appId: '1:1006184410986:web:b5b1549dc15626b84cff13',
    messagingSenderId: '1006184410986',
    projectId: 'greencare-59910',
    authDomain: 'greencare-59910.firebaseapp.com',
    storageBucket: 'greencare-59910.firebasestorage.app',
    measurementId: 'G-PLEW4Z8FKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdEpMlAiXbp-uAwlK2mNR5xgqiQSd-t0A',
    appId: '1:1006184410986:android:0ab2f79c03fcb75f4cff13',
    messagingSenderId: '1006184410986',
    projectId: 'greencare-59910',
    storageBucket: 'greencare-59910.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBced6EFxtfF3D-XFRc907-OnA8piJKWKI',
    appId: '1:1006184410986:ios:b0c3c03f0e794c7b4cff13',
    messagingSenderId: '1006184410986',
    projectId: 'greencare-59910',
    storageBucket: 'greencare-59910.firebasestorage.app',
    iosBundleId: 'com.example.greencare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBced6EFxtfF3D-XFRc907-OnA8piJKWKI',
    appId: '1:1006184410986:ios:b0c3c03f0e794c7b4cff13',
    messagingSenderId: '1006184410986',
    projectId: 'greencare-59910',
    storageBucket: 'greencare-59910.firebasestorage.app',
    iosBundleId: 'com.example.greencare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKZWpi8JHWtIGZ1KAXCBKEGogTjDrbuIU',
    appId: '1:1006184410986:web:40f9df95473a213c4cff13',
    messagingSenderId: '1006184410986',
    projectId: 'greencare-59910',
    authDomain: 'greencare-59910.firebaseapp.com',
    storageBucket: 'greencare-59910.firebasestorage.app',
    measurementId: 'G-EEVMS0YP99',
  );
}
